/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Logo: typeof import('./src/components/Logo.vue')['default']
    Seprator: typeof import('./src/components/Seprator.vue')['default']
    ToggleButton: typeof import('./src/components/ToggleButton.vue')['default']
  }
}
